Add files via upload

diff --git a/alp-setup b/alp-setup
--- a/alp-setup
+++ b/alp-setup
@@ -1,114 +1,344 @@
 #!/bin/ash
 
-#=============================
-# Initialize ALPINE SETUP
-#=============================
-if [[ $EUID -ne 0 ]]; then
-   echo
-   echo "ERROR - This script must be run as root" 
-   echo
-   exit 1
-fi
-
 # Setup global variables
 AUTHOR="Martin Boni"
 VER="1.0.1"
 WORKDIR="$HOME/alpine"
 REPO="https://github.com/martyb95/alpine.git"
+LOG="$HOME/alpine-setup.log"
 
+logfile="./update-alpine.log"
+fhosts="/etc/hosts"
+fhostname="/etc/hostname"
+finterfaces="/etc/network/interfaces"
+fsshd="/etc/ssh/sshd_config"
+fssh="/etc/ssh/ssh_config"
+frepo="/etc/apk/repositories"
+fprof="/etc/profile"
+retval=''
 
 
 #================================
 #   Function Definitions
 #================================
-function GetInput() {
-unset retval
-while [ -z $retval ]; do
-    echo -n "$1"
-    unset retval
-    read retval
-    if [ -z $retval ]; then
-       if [ ! -z $2 ]; then
-          retval=$2
-       fi
+GetInput() {
+  unset retval
+  if [ -z $2 ]; then printf "%s " "$1"; else printf "%s [%s]: " "$1" "$2"; fi
+  IFS="~"
+  read retval
+  if [ -z $retval ]; then retval=$2 ; fi  
+  retval=$(echo $retval | sed 's/^[ \t]*//;s/[ \t]*$//')
+  unset IFS
+  return 0
+}
+
+Center() {
+    # Set input parameters
+    local text=$(echo "$1" | xargs)         # trimmed text to center
+
+    if [ ${#text} -gt $2 ]; then
+       retvar="$text"
+       return 1
     fi
-done
-retval=${retval//[$' ~\t']/}
+
+    printf '%*s%s' "$(( $(($2 / 2)) + $((${#text} / 2)) ))" "$text"
+    return 0
+}
+
+PrintHdr() {
+   local dash1=$(printf "%34s" | tr " " "-")
+   local dash2=$(printf "%25s" | tr " " "-")
+   local dash3=$(printf "%63s" | tr " " "-")
+
+   clear
+   printf "\n\n+%s+\n" "$dash3"
+   printf "++%s++%s++\n" "$dash1" "$dash2"
+   printf "||%34s||%10s %-14s||\n"
+   printf "||%34s||%10s %-14s||\n" " " "Author:" "$AUTHOR"
+   printf "||%-34s||%10s %-14s||\n" "$(Center "$1" 34)" "Version:" "$VER"
+   printf "||%34s||%10s %-14s||\n" " " "Date:" "$(date '+%Y-%m-%d')"
+   printf "||%34s||%10s %-14s||\n"
+   printf "++%s++%s++\n" "$dash1" "$dash2"
+   printf "+%s+\n" "$dash3"
+   
+   if [ -f $LOG ]; then rm -f $LOG; fi
+   printf "===== %s =====\t\t%s\n\n" "$1" "$(date '+%Y-%m-%d')" > $LOG
+}
+
+SectionHdr() {
+   local dash3=$(printf "%63s" | tr " " "-")
+   printf "\n+%s+\n" "$dash3"
+   printf "|  %-61s|\n" "$(Center "$1" 61)"
+   printf "+%s+\n" "$dash3"
+   if [ -z $2 ]; then printf "|%63s|\n" " "  ; fi
+}
+
+SectionFtr() {
+   local dash3=$(printf "%63s" | tr " " "-")
+   if [ -z $1 ]; then printf "|%63s|\n" " "  ; fi
+   printf "+%s+\n" "$dash3"
+}
+
+SectionRow() {
+   printf "|  %-44s[%-12s]   |\n" "$1" "$(Center "$2" 12)"
+}
+
+CheckPriv() {
+	#=============================
+	# Initialize ALPINE SETUP
+	#=============================
+	if [[ $(id -u) -ne 0 ]]; then
+	   printf "\n\n%s\n\n" "ERROR - This script must be run with elevated privileges" 
+	   exit 1
+	fi
+
+	echo "====== Check Privileges ================" >> $LOG
+	SectionRow "Check for Elevated Privileges" "User: $(whoami)"   
+
+}
+
+UpdateRepos() {
+   echo "====== APK UPDATE ================" >> $LOG
+   apk update >> $LOG
+   SectionRow "Repository Updates" "UP-TO-DATE"
+   
+   echo "====== APK UPGRADE ================" >> $LOG
+   apk upgrade >> LOG
+   SectionRow "Repository Upgrades" "COMPLETED"
+}
+
+InstallPkgs() {
+   echo "====== APK ADD BASH ================" >> $LOG
+   apk add bash >> $LOG
+   SectionRow "Adding BASH package" "ADDED"
+   
+   echo "====== APK ADD NANO ================" >> $LOG
+   apk add nano >> $LOG
+   SectionRow "Adding NANO editor package" "ADDED"
+
+   echo "====== APK ADD GIT ================" >> $LOG
+   apk add git >> $LOG
+   SectionRow "Adding GIT package" "ADDED"   
+   
+   echo "====== APK UPDATE ================" >> $LOG
+   apk update >> $LOG
+   SectionRow "Updating Repository with Updates" "COMPLETED"   
+}
+
+SetupGIT () {
+	#  Check for existing alpine directory
+	echo "====== CHECKING FOR GIT DIRECTORY ================" >> $LOG
+	if [[ ! -d $WORKDIR ]]; then
+		echo "====== CD $HOME ================" >> $LOG
+		chdir $HOME  >> $LOG
+		SectionRow "CD to $HOME Directory" "CHANGED"
+
+        echo "====== GIT CLONE $REPO ======" >> $LOG   
+		git clone $REPO  >> $LOG
+		SectionRow "Cloning ALPINE Repository" "DONE"
+	else
+        SectionRow "Clone ALPINE Repository from GITHUB" "BYPASSED"
+	fi
+}
+
+ProcessGIT() {
+	#  change intop alpine and update permissions
+    echo "====== CD $WORKDIR ======" >> $LOG   
+	cd $WORKDIR  >> $LOG
+	SectionRow "Changing to $WORKDIR" "CHANGED"
+	
+    echo "====== CHMOD +X * ======" >> $LOG   
+	chmod +x *  >> $LOG
+	SectionRow "Set EXECUTE permissions on all scripts" "DONE"
+
+    echo "====== CD PACKAGES DIRECTORY ======" >> $LOG   
+	cd packages
+	SectionRow "Changing to $WORKDIR/packages" "CHANGED"
+
+    echo "====== CHMOD +X * ======" >> $LOG   
+	chmod +x *  >> $LOG
+	SectionRow "Set EXECUTE permissions on all scripts" "DONE"
+}
+
+AddUser() {
+    local USR="$1"
+    echo "====== CHECK FOR USER $USR ======" >> $LOG   
+	if [[ $(id -u "$USR") -ne 0 ]]; then 
+        echo "====== USER $USR ALREADY EXISTS ======" >> $LOG   
+    	SectionRow "Add User $USR" "BYPASSED"
+	else
+        echo "====== Adding User $USR =====" >> $LOG
+		adduser -G wheel "$USR"  >> $LOG
+    	SectionRow "Add User $USR" "ADDED"
+	fi
+
+	echo "====== CD $WORKDIR/ssh/ ======" >> $LOG
+	cd $WORKDIR/ssh >> $LOG
+   	SectionRow "Changing to $WORKDIR/ssh/" "CHANGED"
+
+	#  Move files to SSH directories
+	echo "===== Moving SSH files to /etc/ssh/ =====" >> $LOG
+	if [[ -f "sshd_config" ]]; then 
+	   mv -f sshd_config /etc/ssh/ >> $LOG
+       SectionRow "Moving SSH files to /etc/ssh/" "MOVED"
+	else
+   	   SectionRow "Moving SSH files to /etc/ssh/" "NOT FOUND"
+	fi
+
+	echo "===== CREATE Directory /home/$USR/.ssh =====" >> $LOG
+	if [[ ! -d "/home/$USR/.ssh" ]]; then 
+	   mkdir /home/$USR/.ssh >> $LOG
+       SectionRow "Creating Directory /home/$USR/.ssh" "CREATED"
+	else 
+       SectionRow "Creating Directory /home/$USR/.ssh" "BYPASSED"
+	fi
+   	
+	echo "===== Moving SSH KEYS to /home/$USR/.ssh =====" >> $LOG
+	if [[ -f "authorized_keys" ]]; then 
+	   mv -f authorized_keys /home/$USR/.ssh >> $LOG
+       SectionRow "Moving SSH KEYS to /home/$USR/.ssh" "MOVED"
+	else
+   	   SectionRow "Moving SSH KEYS to /home/$USR/.ssh" "NOT FOUND"
+	fi
+	
+	echo "===== CREATE Directory /root/.ssh =====" >> $LOG
+	if [[ ! -d "/root/.ssh" ]]; then 
+	   mkdir /root/.ssh >> $LOG
+   	   SectionRow "CREATE Directory /root/.ssh" "CREATED"
+	else
+   	   SectionRow "CREATE Directory /root/.ssh" "BYPASSED"
+	fi
+
+	echo "===== Moving SSH KEYS to /root/.ssh =====" >> $LOG
+	if [[ -f "authorized_keys" ]]; then 
+	   mv -f authorized_keys /root/.ssh >> $LOG
+   	   SectionRow "Moving SSH KEYS to /root/.ssh" "MOVED"
+    else
+   	   SectionRow "Moving SSH KEYS to /root/.ssh" "NOT FOUND"
+	fi
+	
+	echo "====== CD $HOME ======" >> $LOG
+	cd $HOME >> $LOG
+   	SectionRow "Changing to $HOME" "CHANGED"
+
+	echo "===== Restart the SSH Daemon =====" >> $LOG
+	service sshd restart >> $LOG
+   	SectionRow "Restart the SSH Daemo" "RESTARTED"
+}
+
+MoveScripts() {
+	#  Move scripts to /USR/SBIN
+	#  change intop alpine and update permissions
+    echo "====== CD $WORKDIR ======" >> $LOG   
+	cd $WORKDIR  >> $LOG
+	SectionRow "Changing to $WORKDIR" "DONE"
+	
+    echo "====== MOVE ALP-SETUP to /USR/SBIN/ ======" >> $LOG   
+	if [[ -f "alp-setup" ]]; then mv -f alp-setup /usr/sbin/  >> $LOG ; fi
+	SectionRow "Moving ALP-SETUP script to /USR/SBIN" "DONE"
+
+    echo "====== MOVE UPDATE-ALP to /USR/SBIN/ ======" >> $LOG   
+	if [[ -f "update-alp" ]]; then mv -f update-alp /usr/sbin/  >> $LOG ; fi
+	SectionRow "Moving UPDATE-ALP script to /USR/SBIN" "DONE"
+
+    echo "====== CD $HOME ======" >> $LOG   
+	cd $HOME  >> $LOG
+	SectionRow "Changing to $HOME" "DONE"
+}
+
+#================================
+#  Get list of network adapters
+#
+#  GetNetAdapters()
+#================================
+GetNetAdapters() {
+    unset retval
+    local tmp=$(ip link | awk -F: '$0 !~ "vir|veth|dock|^[^0-9]"{print $2;getline}')
+    retval=${tmp//[$' \t']/}
+    retval=${retval//[$'\r\n']/,}
+}
+
+#================================
+#  Get network adapters info
+#
+#  GetAdapterInfo() $1 $2
+#    where $1=network adapter
+#	   $2=dnstype, hostname, 
+#             ipaddress, netmask, 
+#             gateway
+#================================
+GetAdapterInfo() {
+unset retval
+if [ ! -z $1 ]; then
+   if [ ! -z $2 ]; then
+      #local tmp=${2^^}  #THIS CAUSED AN ERROR
+      local tmp="$2"        
+      if [ $tmp == "DNSTYPE"  ]; then
+         retval=$(grep -A 4 'iface '$1 $finterfaces | awk '{print $4}')
+      else
+         retval=$(grep -A 4 'iface '$1 $finterfaces | grep $2 | awk '{print $2}')
+      fi
+   fi
+fi
+}
+
+#===================================
+#  Update INTERFACES file for 
+#  static IP address
+#
+#  InterfaceStatic()
+#===================================
+InterfaceStatic() {
+   if [ $dtype == "static" ]; then
+      sed -i "s/hostname $hname/hostname $hostname/" $finterfaces
+      sed -i "s/$ipaddr/$address/" $finterfaces
+      sed -i "s/$nmask/$netmask/" $finterfaces
+      sed -i "s/$gway/$gateway/" $finterfaces
+   else
+      echo "DHCP --> Static Processing"
+      local value="\ \thostname $hostname\n\taddress $address\n\tnetmask $netmask\n\tgateway $gateway"
+      local line=$(grep -nm1 "iface $adapt inet" $finterfaces | cut -d: -f1)
+      sed -i "$((line+1)),$((line+2))d" $finterfaces
+      sed -i "/iface $adapt inet $dnstype/a $value" $finterfaces
+   fi
+}
+
+UpdateProfile() {
+  sed 's/^export PS1=.*/export PS1="\[\033[0;31m\]\342\224\214\342\224\200\[\[\033[0;39m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h\[\033[0;31m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\342\224\224\342\224\200\342\224\200\342\224\200 \[\033[0m\]\[\e[01;33m\]\\$\[\e[0m\]"
+/g' $fprof
 }
 
 
 
+#================================
+#   Main Line Code
+#================================
+PrintHdr "Alpine Update Script"
+SectionHdr "User Inputs" "."
+GetInput "Do you wish to exit?" "Yes"
+if [ $retval == "yes"] || [ $retval == "YES" ] || [ $retval == "Yes" ]; then exit 0; fi
+SectionFtr "."
 
-#=====================================
-#  Main Processing
-#=====================================
-clear
-printf "\n\n=====================================================================\n\n"
-printf "   Alpine Setup                                   by: $AUTHOR\n"
-printf "                                             version: $VER\n"
-printf "=====================================================================\n\n"
+SectionHdr "Script Initialization"
+CheckPriv
+UpdateRepos
+InstallPkgs
+SectionFtr
 
-# Update Repositories
-printf "%s\n\n" "Updating Repositories..."
-apk update
-apk upgrade
+SectionHdr "GITHUB Repository"
+SetupGIT
+MoveScripts
+SectionFtr
 
-# Add missing packages
-printf "%s\n\n" "Updating Packages..."
-apk add bash
-apk add nano
-apk add git
+SectionHdr "Setup Users & Permissions"
+AddUser "martin"
+SectionFtr
 
-#  Check for existing alpine directory
-if [[ ! -d $WORKDIR ]]; then
-    chdir $HOME
-    git clone $REPO
-fi
+SectionHdr "Network Setup"
+GetNetAdapters
+GetAdapterInfo "eth0" "ipaddress"
+dtype="static"
+InterfaceStatic
+SectionFtr
 
-#  change intop alpine and update permissions
-printf "%s\n\n" "Updating Script Properties..."
-cd /root/alpine
-chmod +x *
-
-#  Move scripts to /USR/SBIN
-printf "%s\n\n" "Moving scripts to /USR/SBIN/..."
-if [[ -f "alp-setup" ]]; then mv -f alp-setup /usr/sbin/ ; fi
-if [[ -f "update-alp" ]]; then mv -f update-alp /usr/sbin/ ; fi
-cd $HOME
-
-
-
-#  Check for existing MARTIN user
-getent passwd martin  > /dev\null
-if [[ ! $? -eq 0 ]]; then
-    # Add User Martin
-    adduser -G wheel martin
-    printf "%s\n\n" "Added User Martin..."
-fi
-
-#  Get SSH from GITHUB
-printf "%s\n\n" "Getting SSH from GitHub..."
-cd $HOME
-git clone https://github.com/martyb95/ssh
-cd $HOME/ssh
-
-#  Move files to SSH directories
-printf "%s\n\n" "Moving SSH files to..."
-if [[ -f "sshd_config" ]]; then mv -f sshd_config /etc/ssh/ ; fi
-if [[ ! -d "/home/martin/.ssh" ]]; then mkdir /home/martin/.ssh" ; fi
-if [[ -f "authorized_keys" ]]; then mv -f authorized_keys /home/martin/.ssh ; fi
-if [[ ! -d "/root/.ssh" ]]; then mkdir /root/.ssh" ; fi
-if [[ -f "authorized_keys" ]]; then mv -f authorized_keys /root/.ssh ; fi
-cd $HOME
-service sshd restart
-rm -rf ssh
-
-#  Execute update script
-#if [[ -f "/usr/sbin/update-alp" ]]; then
-#   /usr/sbin/update-alp
-#else  
-#   printf "%s\n\n" "ERROR - Cannot find /usr/sbin/update-alp..."
-#fi
-
-rm -rf alpine
-printf "%s\n\n" "End of Script..."
+UpdateProfile
